# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs apt update
      - name: Run a one-line script
        run: sudo apt update

      # Runs apt upgrade
      - name: Run a one-line script
        run: sudo apt upgrade

      # Runs a set of commands using the runners shell
      - name: edit file --- /etc/modules-load.d/k8s.conf
        run: |
          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
          br_netfilter
          EOF
      - name: edit file --- /etc/sysctl.d/k8s.conf
        run: |
          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
      - name: cmd --- sudo sysctl --system
        run: |
          sudo sysctl --system

      - name: cmd --- libseccomp2
        run: |
          sudo echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
          apt update
          apt install -y -t buster-backports libseccomp2 || apt update -y -t buster-backports libseccomp2



